name: Build Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node (Prettier)
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Prettier (for formatting)
        run: npm install -g prettier

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y pandoc jq

      - name: Build site
        run: bash ./build.sh
